### PR TITLE
[TAAS-85] Upgrade to Python3

### PR DESCRIPTION
**Pull request by lazysoundsystem**
https://humanitarian.atlassian.net/projects/TAAS/issues/TAAS-85

A couple of minor changes to prevent errors and to replace the codeclimate tests, detailed on the ticket.

This PR should test whether the Travis changes are okay.

### CODE REVIEW

**Comment by lazysoundsystem** [comment]
Travis did have some comments - including an objection to `xenon`:
```
0.08s$ xenon xenon -bB -mA -aA
No command 'xenon' found, did you mean:
 Command 'xeno' from package 'xenomai-runtime' (universe)
xenon: command not found
The command "xenon xenon -bB -mA -aA" exited with 127.
```
I'm not sure if this can be/ needs to be added back later.

**Comment by emmajane** [comment]
@lazysoundsystem it looks like Xenon measures code complexity: https://pypi.org/project/xenon/. This is arguably _good to have_ but not necessarily *required* for the project to run...

**Comment by lazysoundsystem** [comment]
@emmajane - yes, I'm also guessing @cafuego will know what the issue is and we'll be able to re-instate it. (I presumed that having it in requirements.txt is enough for travis to load it and know it exists, but apparently not.)

Plus, I'd have to dive quite a bit deeper into Python to even consider making the code more complex!

**Comment by cafuego** [comment]
Hmm, the only xenon I know of is the noble gas :-)

**Comment by cafuego** [comment]
Ok, travis says:
```
ERROR: python-coveralls 2.9.0 has requirement coverage==4.0.3, but you'll have coverage 4.5.3 which is incompatible.
ERROR: xenon 0.5.5 has requirement PyYAML<5.0,>=4.2b1, but you'll have pyyaml 5.1.1 which is incompatible.
```
So I guess we won't be using it for a while.

**Comment by lazysoundsystem** [comment]
@cafuego - Looks like we're at an impasse with Xenon - looks like it can't be added back easily, but can we agree that it doesn't *need* to be added back at this stage?

**Comment by teodorescuserban** [comment]
It doesn't.

**Review by teodorescuserban — APPROVED** [review]

**Pull request merged**
