### PR TITLE
Create .codeclimate.yml

### PR DESCRIPTION
**Pull request by efueger**
- Use this .codeclimate.yml to [customize your Code Climate analysis](https://docs.codeclimate.com/docs/getting-started-configuration). 
- Reach out if you have any questions! [www.codeclimate.com/help](www.codeclimate.com/help)

### CODE REVIEW

**Comment by pjf** [comment]
Oh! The irony as having Travis-ci give us the side-eye about the spacing in another QA tool's config file. :) (It doesn't like that lists aren't indented to the right of their parent keys.)

@efueger : You rock! Thank you for this! If you'll excuse my n00bishness, what do `**` represent in the file paths?

**Comment by pjf** [comment]
@efueger : Also, just to check, can I make changes to `.codeclimate.yml` on a side-branch and see how that works out before integrating it into our main branch? (Possibly by turning them into PRs so CC will test the merged results.)

Thank you again!

~ Paul

**Comment by efueger** [comment]
@pjf - happy to expand on this.

1. The ** asterisks are wildcard characters! Wild and crazy. 
- So, for **.py, that means any files ending with that .py extension. (`paul.py`, `good_question`.py).

2. And changing the .codeclimate.yml on a side branch is a great use case! Once you make changes on your branch, we'll [compare those analysis results](https://docs.codeclimate.com/docs/github#pull-requests) against your default branch. 

A quick note about comparisons (kind of advanced, but good to know). Branch comparisons are based on:
- the head of your branch (the latest commit you've pushed to that branch)
- compared to your merge base.

The merge base is the commit from your defaut branch at which the branch was created.

IF you've made a lot of commits into your default branch since you first created the branch, you might want to consider [rebasing your branch](https://docs.codeclimate.com/docs/branches-and-comparisons) on a newer commit from your default branch. Not ncessary to rebase... just wanted to give you a heads up on how those comparisons work.

**Comment by pjf** [comment]
@efueger : Oh! I'm very familiar with `*` as a wildcard, but I'm guessing `**` is a *recursive* wildcard, making it wilder than all the rest? That's pretty cool. :)

You totally anticipated my next question regarding how we do comparisons. I figured it was either using the merge base, but could also conceivably be the *result* of doing the merge. In the case of us changing our codeclimate file, they'll almost always be the same.

Thank you again for all your help, with this, you rock!

**Comment by pjf** [comment]
@efueger : Merged with great thanks!

**Pull request merged**
