### PR TITLE
[OPS-5306] Bump requirements for requests, flask and pyopenssl as per…

### PR DESCRIPTION
**Pull request by cafuego**
… the demands of the AI Overlords.

### CODE REVIEW

**Comment by pjf** [comment]
Looks good to me! :shipit:

**Comment by cafuego** [comment]
Cheers @pjf. What you doin in here? :-)

**Comment by pjf** [comment]
@cafuego : It's the magic of open source!

Also I hate to see PRs go unreviewed. :)

**Comment by cafuego** [comment]
TAASCRAAS - Taxonomy As As Service Code Reviews As A Service!

**Pull request merged**
