### PR TITLE
Add French-language name

### PR DESCRIPTION
**Pull request by davidmegginson**
Modify the configuration file to include the French-language group name in the JSON output.

### CODE REVIEW

**Comment by emmajane** [comment]
@davidmegginson could we follow the same naming convention as https://github.com/UN-OCHA/taas/blob/master/taas/config.d/countries.yml ? This would give us `label.LANG` instead of `label_LANG`. I'm not sure if you found a specific reason to use the underscore, so do let me know if I've missed something elsewhere?

**Comment by emmajane** [comment]
I'm also wondering if the version should be bumped up? I don't know if there's anyone who is using the JSON (or GSS) with a column count, but adding a column to the middle of the list might affect some folks? I believe if we increment the version number we get a new published dataset? You would need to double check this to confirm though... let me know what you think? It is clearly marked as "beta" so it could be okay to change without further warning?

**Comment by davidmegginson** [comment]
I'll close this and create a new pull request with .LANG instead of _LANG

I'll leave the version naming up to you. Anyone using the HXL version won't have problems with the addition of a new column (ditto for the JSON), so it would just be someone using the non-JSON version and referencing by column number instead of header, which seems unlikely.

**Comment by davidmegginson** [comment]
Reopening. If I switch to the naming convention label.french-short, it will substantively change the structure of the JSON, from

```
"label": "Emergency Shelter and NFI",
"label_fr": "Abris d'urgence et NFI"
```

to

```
"label": {
    "default": "Emergency Shelter and NFI",
    "french-short": "Abris d'urgence et NFI"
}
```

Unlike just adding a new property, that's certain to break code for anyone using the JSON API, and should probably include a major version bump. For now, I suggest going taking "label_fr" as the lesser of two evils for backwards-compatibility, until you want to a big update.

**Comment by emmajane** [comment]
(copied from my email)

Yes, you're right that it's better not to change the structure of the output without also changing the version number. Annoying as we can't add the new method without changing the old method ... AND because it's on GitHub pages I don't have a way of checking stats to see if it's being used.

The JSON file is versioned though (yay), so I think we could put out beta-v2 with the French language names and leave v1 as English only.

https://github.com/UN-OCHA/taas-data/tree/master/json/beta-v1

I think this means editing the config file to bump the version number in the same file that you edited (and possibly you can have both as it's YML...):
https://github.com/UN-OCHA/taas/blob/master/taas/config.d/global_coordination_groups.yml

Shall we give it a try to add a v2 section and see if it breaks the tests?

**Pull request closed without merging**
