### PR TITLE
[OPS-2369] Streamline docker workflow for easier container re-use.

### PR DESCRIPTION
**Pull request by cafuego**
* Add Makefile steps to build and tag a re-usable docker image
* Add label metadata to the Dockerfile.
* Concatenate Dockerfile RUN steps for fewer image layers. Not less image layers. This is important.
* Set a default workdir and entrypoint in Dockerfile.
* Update the README appropriately.
* 🍨

### CODE REVIEW

**Comment by pjf** [comment]
@cafuego : You rock, thank you!

I'm running an old version of Docker locally, so I'm upgrading that so I can test this with the `--build-arg` switches.

I'm guessing `make tag` is safe for me to do as long as I don't go pushing the build?

Thanks again!!

~ Paul

**Comment by cafuego** [comment]
You'll want to probably go to 1.12.6 at a minimum, to match what's on the prod server currently.

We're not really using the hubbed image yet, so you're free to tag and push for the moment :-)

**Comment by pjf** [comment]
Testing now. So far a few hiccups upgrading docker, but otherwise going well.

@cafuego : I'm guess those badgers are reporting on the dockerhub image?

badger

**Comment by cafuego** [comment]
@pjf Possibly?

honeybadger

**Comment by pjf** [comment]
Hooray! Got it working. Adding a minor patching commit and merging with *docking huge thanks*. <3 <3 <3

**Pull request merged**
